import "./globals.css";
import styles from "./layout.module.scss";
import Navbar from "../components/navbar.component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Navbar />
      <body className={styles.header}>{children}</body>
    </html>
  );
}
