import "../app/styles/global.css";
import "../app/styles/navbar.styles.css";
import "../app/styles/carousel.styles.css";
import "../app/styles/footer.styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
