// import Head from "next/head";
import Script from "next/script";
import "../app/styles/global.css";
import "../app/styles/navbar.styles.css";
import "../app/styles/carousel.styles.css";
import "../app/styles/footer.styles.css";

// import { Oleo_Script } from "@next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// const oleoScript = Oleo_Script({
//   weight: "400",
//   subsets: ["latin"],
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        src="https://kit.fontawesome.com/85d5839673.js"
        crossOrigin="anonymous"
      ></Script>
      <body>{children}</body>
    </html>
  );
}
